[keyboard]
name = "TrhAlice"
product_name = "Alice73"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "TRH"
chip = "rp2040"

[matrix]
# Input and output pins are mandatory
input_pins = ["PIN_6", "PIN_7", "PIN_8", "PIN_9", "PIN_10"]
output_pins = ["PIN_4", "PIN_28", "PIN_27", "PIN_26", "PIN_22", "PIN_21", "PIN_20", "PIN_19", "PIN_18", "PIN_17", "PIN_16", "PIN_15", "PIN_14", "PIN_13", "PIN_12", "PIN_11"]

[layout]
rows = 5
cols = 16
layers = 4
keymap = [
    [
        ["Escape", "Grave",    "Kc1", "Kc2", "Kc3",  "Kc4", "Kc5",  "Kc6",    "Kc7", "Kc8",   "Kc9",          "Kc0",                  "Minus",       "Equal",        "Backspace", "_"],
        ["MO(4)",  "Tab",      "Q",    "W",  "E",    "R",   "T",     "Y",     "U",   "I",     "O",            "P",                    "LeftBracket", "RightBracket", "Backslash", "_"],
        ["MO(3)",  "CapsLock", "A",    "S",  "D",    "F",   "G",     "H",     "J",   "K",     "L",            "Semicolon",            "Quote",        "_",            "Enter",     "_"],
        ["MO(2)",  "LShift",   "Z",    "X",  "C",    "V",   "B",     "B",     "N",   "M",     "Comma",        "Dot",                  "Slash",        "RShift",       "Up",        "Delete"],
        ["MO(1)",  "LCtrl",    "LGui", "_",  "LAlt", "_",   "Space", "RCtrl", "_",   "Space", "SHIFTED(Kc9)", "SHIFTED(LeftBracket)", "RShift",       "Left",         "Down",      "Right"]
    ],
    [
        ["_",      "_",        "F1",   "F2", "F3",   "F4",  "F5",    "F6",    "F7",  "F8",    "F9",           "F10",                  "F11",         "F12",          "Delete",    "_"],
        ["_",      "_",        "_",    "_",  "_",    "_",   "_",     "_",     "_",   "_",     "_",            "_",                     "_",           "_",            "_",         "_"],
        ["_",      "_",        "_",    "_",  "_",    "_",   "_",     "_",     "_",   "_",     "_",            "_",                     "_",           "_",            "_",         "_"],
        ["_",      "_",        "_",    "_",  "_",    "_",   "_",     "_",     "_",   "_",     "_",            "_",                     "_",           "_",            "PageUp",    "_"],
        ["_",      "_",        "_",    "_",  "_",    "_",   "_",     "_",     "_",   "_",     "_",            "_",                     "_",           "Home",         "PageDown",  "End"]
    ]
]

[storage]
# Storage feature is enabled by default
enabled = true
num_sectors = 32

